### ISSUE TITLE
Reconnect. Cql::NotConnectedError

### ISSUE THREAD

**Issue by brlo** [cequel/cequel#115]
How I can achieve reconnection if I lose my current connection?

`cequel.yml`

```
development:
  hosts:
    - '192.168.1.1'
    - '192.168.1.2'
  port: 9042
  keyspace: test_cequel
```

Thanks
