### ISSUE TITLE
Cql::Client.connect options

### ISSUE THREAD

**Issue by twoofy** [cequel/cequel#142]
Cql::Client.connect supports options that Cequel seems to be ignoring.    The ones we specifically are using (some of which could/should probably be removed) are: connection_timeout, cql_version, and default_consistency.

I believe the issue (if there is one) is due to this code in lib/cequel/metal/keyspace.rb:

```
  def client_options
    {hosts: hosts, port: port}.tap do |options|
      options[:credentials] = credentials if credentials
    end
  end
```

Any plans to support more of the connect options in Cql::Client.connect?

**Comment by cmbaron** [comment]
I took a stab at exposing ssl options based on https://gist.github.com/jasonmk/be5257c2b846c2b74c6c 
Any advice on how to build a test for https://github.com/cmbaron/cequel/commit/a342e1d6fde6eef8f2131dcf2dbfc5cd8e165e9c given cassandra does not seem to support ssl and non-ssl concurrently?

**Comment by bobbrez** [comment]
It seems like `auth_provider` may be needed in cases of using [Instaclustr on Heroku](https://devcenter.heroku.com/articles/instaclustr#using-with-ruby). Testing this out on a project, using a config file like

```yaml
production:
  hosts: <%= ENV['IC_CONTACT_POINTS'].to_s.split(',') %>
  port: <%= ENV['IC_PORT'] %>
  keyspace: atlas_production
  username: <%= ENV['IC_USER'] %>
  password: <%= ENV['IC_PASSWORD'] %>
  max_retries: 3
  retry_delay: 0.5
  newrelic: true
  replication:
    class: NetworkTopologyStrategy
    replication_factor: 1
    datacenter1: US_EAST_1
```
Will throw `Cassandra::Errors::AuthenticationError: Server requested authentication, but client was not configured to authenticate` on any attempt to connect to the cluster, but using an adapter resolves the issue. I'll try to put together a PR for this.
