### ISSUE TITLE
Cannot connect to Instaclustr

### ISSUE THREAD

**Issue by aistech** [cequel/cequel#302]
Hi,

I am having a hard time trying to connect to an Instaclustr instance when running the rake tasks. Here is the stacktrace:

```
Cql::AuthenticationError: Auth provider raised an error: can't convert nil into Integer
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cql-rb-2.0.5/lib/cql/client/client.rb:523:in `connect'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cql-rb-2.0.5/lib/cql/client.rb:134:in `connect'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cequel-1.5.0/lib/cequel/metal/keyspace.rb:254:in `block in raw_client'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cequel-1.5.0/lib/cequel/metal/keyspace.rb:253:in `raw_client'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cequel-1.5.0/lib/cequel/metal/keyspace.rb:157:in `block in client'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cequel-1.5.0/lib/cequel/metal/keyspace.rb:156:in `client'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cequel-1.5.0/lib/cequel/metal/keyspace.rb:195:in `block in execute_with_consistency'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cequel-1.5.0/lib/cequel/metal/request_logger.rb:30:in `log'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cequel-1.5.0/lib/cequel/metal/keyspace.rb:193:in `execute_with_consistency'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cequel-1.5.0/lib/cequel/metal/keyspace.rb:177:in `execute'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cequel-1.5.0/lib/cequel/schema/keyspace.rb:75:in `create!'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/cequel-1.5.0/lib/cequel/record/tasks.rb:9:in `block (3 levels) in <top (required)>'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide.rb:88:in `debug_load'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide.rb:88:in `debug_program'
/<HOME>/.rvm/gems/ruby-2.3.0@gemset/gems/ruby-debug-ide-0.6.1.beta2/bin/rdebug-ide:130:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
Tasks: TOP => cequel:keyspace:create
(See full trace by running task with --trace)
```
cequel.yml

```
staging:
  hosts:
    - 'ip1'
    - 'ip2'
  port: 9042
  keyspace: project_staging
  username: 'user'
  password: 'password'
  max_retries: 3
  retry_delay: 0.5
  newrelic: true
  replication:
    class: NetworkTopologyStrategy
    replication_factor: 2
    datacenter1: AWS_VPC_US_WEST_2
```

Can any one help me?
