### ISSUE TITLE
rake cequel:keyspace:create

### ISSUE THREAD

**Issue by t33m** [cequel/cequel#341]
Got following error
```
$ rake cequel:keyspace:create
rake aborted!
NoMethodError: undefined method `deep_symbolize_keys' for nil:NilClass
/usr/local/lib/ruby/gems/2.3.0/gems/cequel-2.0.2/lib/cequel/record/railtie.rb:56:in `configuration'
/usr/local/lib/ruby/gems/2.3.0/gems/cequel-2.0.2/lib/cequel/record/railtie.rb:18:in `block in <class:Railtie>'
/usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:30:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/application.rb:352:in `initialize!'
/Users/timur/Desktop/tmp/risms/api/config/environment.rb:5:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/application.rb:328:in `require_environment!'
/usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => cequel:keyspace:create => environment
(See full trace by running task with --trace)
```

my cequel.yml
```
# development:
#   host: '192.168.59.103'
#   port: 9042
#   keyspace: api_development
#   max_retries: 3
#   retry_delay: 0.5
#   newrelic: false

test:
  host: '192.168.59.103'
  port: 9042
  keyspace: api_test
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

production:
  hosts:
    - '192.168.59.103'
  port: 9042
  keyspace: api_production
  username: 'myappuser'
  password: 'password1'
  max_retries: 3
  retry_delay: 0.5
  newrelic: true
  replication:
    class: SimpleStrategy
    replication_factor: 1
# replication:
#   class: NetworkTopologyStrategy
#   datacenter1: 3
#   datacenter2: 2
# durable_writes: false
```

index api_development already exists.
