### ISSUE TITLE
Cequel Sinatra

### ISSUE THREAD

**Issue by mastermindg** [cequel/cequel#369]
I'm using Sinatra for my API because I've separated out the "view" component for scalability-purposes. Will cequel work with Sinatra and other Rack-based frameworks (other than Rails)?

**Comment by mastermindg** [comment]
Follow-up question: The README says that Rails is not required but config/cequel.yml is. Is there anything else required other than?:

```
development:
  host: '127.0.0.1'
  port: 9042
  keyspace: Blog
```
